### ISSUE TITLE
recommendations

### ISSUE THREAD

**Issue by Caspain** [Caspain/MOHExpertSystem#5]
shervain fix the returned value for recommenations. no x,y,z. only low, slightly etc should be returned.
just push to master branch.

**Comment by direwolf2494** [comment]
sending the risk level to the risk_treatement rule with a variable should return the list containing the different treatments. The only things that need modifying atm, is the data within the list, eg. instead of 'X', it should be like 'drink more water'.

**Comment by Caspain** [comment]
just modify it, to return only levels. such as low,high etc. i already included the recommendations.
